### ISSUE TITLE
MSRV

### ISSUE THREAD

**Issue by tcharding** [Kixunil/push_decode#2]
What is the MSRV plans for this crate Kix? Are you planning on updating it to 1.63?

**Comment by Kixunil** [comment]
I'll make it such that it'd be compatible with `bitcoin`. So 1.63 currently. But I guess I really want to see GAT eventually so the crate probably only stabilizes at 1.65. (This is non-issue for `bitcoin-primitives` since they don't need to stably require GAT.)

**Comment by tcharding** [comment]
Ok, thanks.
